// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-music-utils.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNMusicUtilsSpec.h"

@interface MusicUtils : NSObject <NativeMusicUtilsSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MusicUtils : NSObject <RCTBridgeModule>
#endif

@end